/**
 * Turns the Docs section into a genuine Qiskit API/gate reference manual
 * (as opposed to the Courses section, which is now pure video curriculum).
 *
 * Adds two new reference docs under Qiskit > Circuits and Operators:
 *   1. "Gate Reference"           — every common gate, its matrix, and Qiskit method
 *   2. "Qiskit Syntax Cheatsheet" — the exact patterns this platform's own
 *                                    Sandbox / Circuit Simulator generate
 *
 * Run with: node backend/scripts/seedGateReferenceDocs.js
 */
const mongoose = require("mongoose");
const path = require("path");
const Doc = require("../models/Doc");
require("dotenv").config({ path: path.join(__dirname, "../../.env") });

const gateReferenceContent = `
<p>Every gate available in this platform's <strong>Circuit Simulator</strong> and <strong>Circuit Challenges</strong> drag-and-drop builder, with its matrix and the exact Qiskit method that implements it.</p>

<h3>Single-Qubit Gates</h3>
<table>
<thead><tr><th>Gate</th><th>Symbol</th><th>Matrix</th><th>Qiskit Method</th><th>Effect</th></tr></thead>
<tbody>
<tr><td>Identity</td><td>I</td><td>$\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}$</td><td><code>qc.id(q)</code></td><td>No-op, used as a spacer</td></tr>
<tr><td>Pauli-X</td><td>X</td><td>$\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}$</td><td><code>qc.x(q)</code></td><td>Bit-flip — quantum NOT</td></tr>
<tr><td>Pauli-Y</td><td>Y</td><td>$\\begin{pmatrix}0&-i\\\\i&0\\end{pmatrix}$</td><td><code>qc.y(q)</code></td><td>Bit-flip + phase-flip</td></tr>
<tr><td>Pauli-Z</td><td>Z</td><td>$\\begin{pmatrix}1&0\\\\0&-1\\end{pmatrix}$</td><td><code>qc.z(q)</code></td><td>Phase-flip on \\(|1\\rangle\\)</td></tr>
<tr><td>Hadamard</td><td>H</td><td>$\\frac{1}{\\sqrt2}\\begin{pmatrix}1&1\\\\1&-1\\end{pmatrix}$</td><td><code>qc.h(q)</code></td><td>Creates equal superposition</td></tr>
<tr><td>Phase (S)</td><td>S</td><td>$\\begin{pmatrix}1&0\\\\0&i\\end{pmatrix}$</td><td><code>qc.s(q)</code></td><td>Quarter-turn phase gate</td></tr>
<tr><td>S-dagger</td><td>S†</td><td>$\\begin{pmatrix}1&0\\\\0&-i\\end{pmatrix}$</td><td><code>qc.sdg(q)</code></td><td>Inverse of S</td></tr>
<tr><td>T gate</td><td>T</td><td>$\\begin{pmatrix}1&0\\\\0&e^{i\\pi/4}\\end{pmatrix}$</td><td><code>qc.t(q)</code></td><td>Eighth-turn phase gate</td></tr>
<tr><td>T-dagger</td><td>T†</td><td>$\\begin{pmatrix}1&0\\\\0&e^{-i\\pi/4}\\end{pmatrix}$</td><td><code>qc.tdg(q)</code></td><td>Inverse of T</td></tr>
<tr><td>Square-root-X</td><td>√X</td><td>$\\frac12\\begin{pmatrix}1{+}i&1{-}i\\\\1{-}i&1{+}i\\end{pmatrix}$</td><td><code>qc.sx(q)</code></td><td>Half bit-flip</td></tr>
</tbody>
</table>

<h3>Parameterized Rotation Gates</h3>
<p>These take an angle \\(\\theta\\) in radians and rotate the qubit's state around an axis of the Bloch sphere.</p>
<table>
<thead><tr><th>Gate</th><th>Matrix</th><th>Qiskit Method</th><th>Axis</th></tr></thead>
<tbody>
<tr><td>Rx(θ)</td><td>$\\begin{pmatrix}\\cos\\frac\\theta2 & -i\\sin\\frac\\theta2\\\\-i\\sin\\frac\\theta2 & \\cos\\frac\\theta2\\end{pmatrix}$</td><td><code>qc.rx(theta, q)</code></td><td>X-axis</td></tr>
<tr><td>Ry(θ)</td><td>$\\begin{pmatrix}\\cos\\frac\\theta2 & -\\sin\\frac\\theta2\\\\\\sin\\frac\\theta2 & \\cos\\frac\\theta2\\end{pmatrix}$</td><td><code>qc.ry(theta, q)</code></td><td>Y-axis</td></tr>
<tr><td>Rz(θ)</td><td>$\\begin{pmatrix}e^{-i\\theta/2}&0\\\\0&e^{i\\theta/2}\\end{pmatrix}$</td><td><code>qc.rz(theta, q)</code></td><td>Z-axis</td></tr>
</tbody>
</table>

<h3>Multi-Qubit Gates</h3>
<table>
<thead><tr><th>Gate</th><th>Qiskit Method</th><th>Effect</th></tr></thead>
<tbody>
<tr><td>CNOT (CX)</td><td><code>qc.cx(control, target)</code></td><td>Flips target if control is \\(|1\\rangle\\) — the workhorse of entanglement</td></tr>
<tr><td>Controlled-Z</td><td><code>qc.cz(q0, q1)</code></td><td>Applies Z to target if control is \\(|1\\rangle\\)</td></tr>
<tr><td>SWAP</td><td><code>qc.swap(q0, q1)</code></td><td>Exchanges the states of two qubits</td></tr>
<tr><td>Toffoli (CCX)</td><td><code>qc.ccx(c1, c2, target)</code></td><td>Flips target only if both controls are \\(|1\\rangle\\)</td></tr>
<tr><td>Fredkin (CSWAP)</td><td><code>qc.cswap(control, q0, q1)</code></td><td>Swaps two qubits conditioned on a control</td></tr>
</tbody>
</table>

<h3>Worked Example — Bell State</h3>
<p>Combining H and CX is how every entanglement example on this platform (Sandbox's "Bell State" template, the Entanglement Lab) builds a Bell pair:</p>
<pre><code class="language-python">from qiskit import QuantumCircuit

qc = QuantumCircuit(2)
qc.h(0)       # H|0> = (|0> + |1>) / sqrt(2)
qc.cx(0, 1)   # entangles qubit 1 with qubit 0
qc.measure_all()</code></pre>
`.trim();

const cheatsheetContent = `
<p>The exact Qiskit patterns generated by this platform's <strong>Sandbox</strong> and <strong>Circuit Simulator</strong> — copy these directly into your own notebooks.</p>

<h3>1. Build a Circuit</h3>
<pre><code class="language-python">from qiskit import QuantumCircuit

qc = QuantumCircuit(3)        # 3 qubits, no classical bits
qc = QuantumCircuit(3, 3)     # 3 qubits + 3 classical bits (needed if you call .measure())</code></pre>

<h3>2. Add Gates and Measure</h3>
<pre><code class="language-python">qc.h(0)
qc.cx(0, 1)
qc.measure(0, 0)     # measure qubit 0 into classical bit 0
qc.measure_all()     # or measure everything at once</code></pre>

<h3>3. Draw the Circuit</h3>
<pre><code class="language-python">from qiskit.visualization import circuit_drawer
fig = circuit_drawer(qc, output='mpl')
display(fig)   # this platform's Sandbox captures display() calls as images</code></pre>

<h3>4. Simulate on Qiskit Aer</h3>
<pre><code class="language-python">from qiskit_aer import Aer
from qiskit import transpile

simulator = Aer.get_backend('aer_simulator')
compiled = transpile(qc, simulator)
job = simulator.run(compiled, shots=1000)
counts = job.result().get_counts()
print(counts)   # e.g. {'000': 498, '111': 502}</code></pre>

<h3>5. Exact (Noiseless) State — Statevector</h3>
<p>Useful when you want the theoretical probabilities instead of sampled shot counts (this is what powers this platform's Probability Heatmap):</p>
<pre><code class="language-python">from qiskit.quantum_info import Statevector
import numpy as np

sv = Statevector.from_instruction(qc)   # qc must have NO measure gates
probabilities = np.abs(sv.data) ** 2</code></pre>

<h3>6. Visualize Results</h3>
<pre><code class="language-python">from qiskit.visualization import plot_histogram, plot_bloch_multivector

fig = plot_histogram(counts)
display(fig)

fig2 = plot_bloch_multivector(sv)
display(fig2)</code></pre>

<h3>7. Other Backends (PennyLane / Cirq)</h3>
<p>The Circuit Simulator's backend selector generates equivalent code for PennyLane and Cirq. Quick reference:</p>
<table>
<thead><tr><th>Task</th><th>Qiskit</th><th>PennyLane</th><th>Cirq</th></tr></thead>
<tbody>
<tr><td>Hadamard</td><td><code>qc.h(0)</code></td><td><code>qml.Hadamard(wires=0)</code></td><td><code>cirq.H(q0)</code></td></tr>
<tr><td>CNOT</td><td><code>qc.cx(0,1)</code></td><td><code>qml.CNOT(wires=[0,1])</code></td><td><code>cirq.CNOT(q0,q1)</code></td></tr>
<tr><td>Sample counts</td><td><code>job.result().get_counts()</code></td><td><code>qml.counts()</code></td><td><code>result.histogram(key=...)</code></td></tr>
</tbody>
</table>
`.trim();

async function run() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to MongoDB for reference-docs update");

    // Make room right after "Overview" for the new "Gate Reference" doc
    await Doc.updateMany(
      { section: "Qiskit", subsection: "Circuits and Operators", order: { $gte: 1 } },
      { $inc: { order: 1 } }
    );

    await Doc.findOneAndUpdate(
      { section: "Qiskit", subsection: "Circuits and Operators", title: "Gate Reference" },
      {
        section: "Qiskit",
        subsection: "Circuits and Operators",
        title: "Gate Reference",
        sectionOrder: 1,
        subsectionOrder: 0,
        order: 1,
        content: gateReferenceContent,
      },
      { upsert: true, new: true }
    );
    console.log("Upserted: Gate Reference");

    await Doc.findOneAndUpdate(
      { section: "Qiskit", subsection: "Cheatsheets", title: "Qiskit Syntax Cheatsheet" },
      {
        section: "Qiskit",
        subsection: "Cheatsheets",
        title: "Qiskit Syntax Cheatsheet",
        sectionOrder: 1,
        subsectionOrder: 6,
        order: 0,
        content: cheatsheetContent,
      },
      { upsert: true, new: true }
    );
    console.log("Upserted: Qiskit Syntax Cheatsheet");

    process.exit(0);
  } catch (error) {
    console.error("Error updating reference docs:", error);
    process.exit(1);
  }
}

run();
