import { marked } from "marked";

// Configure marked for GitHub Flavored Markdown with clean line breaks
marked.setOptions({
  gfm: true,
  breaks: true,
});

/**
 * Escapes HTML characters
 */
function escapeHtml(text) {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

/**
 * Clean malformed LaTeX artifacts generated by LLMs
 */
function cleanMath(math) {
  return math
    // Fix malformed subscripts generated by the model: *{q_0} / *{q\_0} → _{q_0}
    .replace(/\\\*{(q\\?_?\d+)}/g, (_, qubit) => `\\_{${qubit.replace(/\\_/g, "_")}}`)
    // Remove decorative semicolons around LaTeX operators
    .replace(
      /;\s*(\\(?:otimes|longrightarrow|rightarrow|xrightarrow|cdot|times))\s*;/g,
      " $1 "
    );
}

/**
 * Auto-delimit bare LaTeX math commands and complete formulas that the LLM forgot to enclose in $...$
 */
function autoDelimitBareMath(text) {
  if (!text || typeof text !== "string") return text || "";

  // 1. Protect existing $...$ and $$...$$ so we never touch or nest inside them
  const protectedMath = [];
  let s = text.replace(/\$\$[\s\S]*?\$\$|(?<!\$)\$[^$\n]+?\$(?!\$)/g, (m) => {
    const id = protectedMath.length;
    protectedMath.push(m);
    return `ZZZEXISTINGMATH${id}ZZZ`;
  });

  // 2. Protect inline code `...` and code blocks ```...```
  const protectedCode = [];
  s = s.replace(/```[\s\S]*?```|`[^`\n]+`/g, (m) => {
    const id = protectedCode.length;
    protectedCode.push(m);
    return `ZZZEXISTINGCODE${id}ZZZ`;
  });

  // 3. Match complete mathematical formulas and clauses
  // Math elements:
  // - LaTeX command with arguments: \\[a-zA-Z]+(?:\{[^{}\n]*\}|\[[^\]\n]*\])*
  // - Dirac expressions: \|[^|\s>\n]*(?:\\rangle|>)
  // - Exponential operators: e\^\{?[^{}\s\n]+\}?
  // - Subscripted/superscripted variables: [a-zA-Z](?:_[a-zA-Z0-9{}]+|\^[a-zA-Z0-9{}]+)+
  // - Standalone sub/superscript operators: [_^]\{?[^{}\s\n]+\}?
  // - Absolute value / norm / Dirac pipes: \|
  // - Math operators: [=+\-*/<>±≈≤≥→∝⊗⊕~] | \\(?:to|le|ge|approx|propto|otimes|pm|cdot|times|equiv|ne)
  // - Numbers: \b\d+(?:\.\d+)?\b
  // - Single-letter variable ONLY: \b[a-zA-Z]\b (excludes multi-letter English words)
  // - Delimiters: [()\[\]{}]
  // - Spacing within math: \\,|\\;|\\!
  const mathToken = `(?:\\\\[a-zA-Z]+(?:\\{[^{}\\n]*\\}|\\[[^\\]\\n]*\\])*|\\|[^|\\s>\\n]*(?:\\\\rangle|>)|e\\^\\{?[^{}\\s\\n]+\\}?|[a-zA-Z](?:_[a-zA-Z0-9{}]+|\\^[a-zA-Z0-9{}]+)+|[_^]\\{?[^{}\\s\\n]+\\}?|\\||\\\\(?:to|le|ge|approx|propto|otimes|pm|cdot|times|equiv|ne)|[=+\\-\\*/<>±≈≤≥→∝⊗⊕~]|[\\(\\)\\[\\]\\{\\}]|\\\\,|\\\\;|\\\\!|\\b\\d+(?:\\.\\d+)?\\b|\\b[a-zA-Z]\\b)`;

  const mathExprRegex = new RegExp(
    `(${mathToken}(?:\\s*${mathToken})*)`,
    "g"
  );

  s = s.replace(mathExprRegex, (match) => {
    // Math expression must have an anchor:
    // A backslash command, a Dirac ket, an exponent, or a subscripted/superscripted variable
    const hasAnchor = /\\[a-zA-Z]+|\|[^|\n>]+(?:\rangle|>)|e\^\{|[a-zA-Z]_[a-zA-Z0-9]+|[a-zA-Z]\^[a-zA-Z0-9]+/.test(match);
    if (!hasAnchor) return match;

    let expr = match.trim();

    // Separate trailing sentence punctuation (.,;:!?)
    let trailingPunct = "";
    const punctMatch = expr.match(/([.,;:!?]+)$/);
    if (punctMatch) {
      trailingPunct = punctMatch[1];
      expr = expr.slice(0, -trailingPunct.length).trim();
    }

    // Separate leading/trailing unmatched parentheses
    let leadingParen = "";
    if (expr.startsWith("(") && (expr.split("(").length > expr.split(")").length)) {
      leadingParen = "(";
      expr = expr.slice(1).trim();
    }
    let trailingParen = "";
    if (expr.endsWith(")") && (expr.split(")").length > expr.split("(").length)) {
      trailingParen = ")";
      expr = expr.slice(0, -1).trim();
    }

    if (!expr) return match;

    return `${leadingParen}$${expr}$${trailingParen}${trailingPunct}`;
  });

  // Restore protected items
  protectedCode.forEach((code, i) => {
    s = s.replace(`ZZZEXISTINGCODE${i}ZZZ`, code);
  });
  protectedMath.forEach((math, i) => {
    s = s.replace(`ZZZEXISTINGMATH${i}ZZZ`, math);
  });

  return s;
}

/**
 * Normalizes math brackets: \[...\] → $$...$$, \(...\) → $...$
 */
function normalizeMathDelimiters(text) {
  if (!text || typeof text !== "string") return text || "";

  let normalized = text;

  // Convert \\[...\\] → $$...$$
  normalized = normalized.replace(
    /\\\[([\s\S]*?)\\\]/g,
    (_, math) => `$$${cleanMath(math)}$$`
  );

  // Convert \\(...\\) → $...$
  normalized = normalized.replace(
    /\\\(([\s\S]*?)\\\)/g,
    (_, math) => `$${cleanMath(math)}$`
  );

  // Clean existing $$...$$ blocks
  normalized = normalized.replace(
    /\$\$([\s\S]*?)\$\$/g,
    (_, math) => `$$${cleanMath(math)}$$`
  );

  // Clean existing $...$ blocks
  normalized = normalized.replace(
    /(?<!\$)\$([^$\n]+?)\$(?!\$)/g,
    (_, math) => `$${cleanMath(math)}$`
  );

  return normalized;
}

/**
 * Protect math blocks so marked doesn't mangle underscores, asterisks, or backslashes
 */
function protectMathBlocks(text) {
  const mathBlocks = [];

  const protectedText = text.replace(
    /\$\$[\s\S]*?\$\$|(?<!\$)\$[^$\n]*?\$(?!\$)/g,
    (match) => {
      const index = mathBlocks.length;
      mathBlocks.push(match);
      return `QUANTIVAMATHBLOCK${index}END`;
    }
  );

  return { protectedText, mathBlocks };
}

/**
 * Restore protected math blocks back into the parsed HTML
 */
function restoreMathBlocks(html, mathBlocks) {
  let restored = html;

  mathBlocks.forEach((math, index) => {
    const token = `QUANTIVAMATHBLOCK${index}END`;
    restored = restored.replace(token, escapeHtml(math));
  });

  return restored;
}

/**
 * Main parser: takes raw Markdown + LaTeX string, converts to HTML with protected KaTeX delimiters
 */
export function parseMathMarkdown(rawText) {
  if (!rawText || typeof rawText !== "string") return "";

  // 1. Auto-wrap bare math/Dirac notation that lacks $
  const autoDelimited = autoDelimitBareMath(rawText);

  // 2. Standardize delimiters
  const normalized = normalizeMathDelimiters(autoDelimited);

  // 3. Protect math from marked parsing
  const { protectedText, mathBlocks } = protectMathBlocks(normalized);

  // 4. Run marked on markdown text
  const rawHtml = marked.parse(protectedText);

  // 5. Restore math blocks
  const finalHtml = restoreMathBlocks(rawHtml, mathBlocks);

  return finalHtml;
}

export default parseMathMarkdown;
